<?php
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;
class SeedPermissionFoundation extends Migration
{
    public function up():void
    {
        $this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'permission_key'=>['type'=>'VARCHAR','constraint'=>150],'module'=>['type'=>'VARCHAR','constraint'=>60],'label'=>['type'=>'VARCHAR','constraint'=>150],'sensitive'=>['type'=>'TINYINT','constraint'=>1,'default'=>0],'created_at'=>['type'=>'DATETIME']]);$this->forge->addKey('id',true);$this->forge->addUniqueKey('permission_key');$this->forge->createTable('permission_definitions');
        $this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'user_id'=>['type'=>'INT','unsigned'=>true],'permission_key'=>['type'=>'VARCHAR','constraint'=>150],'old_state'=>['type'=>'VARCHAR','constraint'=>10,'null'=>true],'new_state'=>['type'=>'VARCHAR','constraint'=>10],'changed_by'=>['type'=>'INT','unsigned'=>true],'created_at'=>['type'=>'DATETIME']]);$this->forge->addKey('id',true);$this->forge->addKey(['user_id','created_at']);$this->forge->createTable('permission_change_history');
        $modules=['dashboard'=>['view','view_financial_usage','view_sending_usage','view_system_health','view_customer_summary'],'contacts'=>['view','create','edit','delete','import','export','merge_duplicates','manage_custom_fields','manage_lists','manage_tags','manage_segments','view_activity','view_suppressed'],'campaigns'=>['view','create','edit','delete_drafts','duplicate','preview','test','submit_for_approval','approve','reject','send','schedule','pause','cancel','export'],'templates'=>['view','create','edit','delete','import','import_from_url','export','manage_folders','publish','restore_versions'],'automations'=>['view','create','edit','activate','pause','delete','view_analytics'],'forms'=>['view','create','edit','publish','delete','export_submissions'],'analytics'=>['view','view_contact_activity','view_recipient_emails','export','view_geographic','view_device'],'team'=>['view','invite','edit','suspend','delete','manage_roles','manage_permissions','assign_workspaces'],'smtp'=>['view','create','edit','test','delete','view_usage','view_errors','assign'],'white_label'=>['view','edit','manage_domain','manage_support','manage_css','manage_emails'],'reports'=>['view','generate_pdf','generate_csv','generate_excel','download','delete'],'settings'=>['view','edit','manage_sending','manage_tracking','manage_api_keys','manage_webhooks','manage_integrations']];$now=date('Y-m-d H:i:s');$rows=[];foreach($modules as$m=>$actions)foreach($actions as$a)$rows[]=['permission_key'=>"{$m}.{$a}",'module'=>$m,'label'=>ucwords(str_replace('_',' ',$a)),'sensitive'=>in_array("{$m}.{$a}",['contacts.export','campaigns.send','campaigns.approve','team.manage_permissions','smtp.edit','settings.manage_api_keys'],true)?1:0,'created_at'=>$now];$this->db->table('permission_definitions')->insertBatch($rows);
        $presets=['Full Administrator'=>['*'],'Manager'=>['dashboard.*','contacts.*','campaigns.*','templates.*','analytics.*','team.view'],'Campaign Manager'=>['campaigns.*','templates.view','analytics.view'],'Campaign Creator'=>['campaigns.view','campaigns.create','campaigns.edit','campaigns.preview','campaigns.test','campaigns.submit_for_approval'],'Campaign Approver'=>['campaigns.view','campaigns.preview','campaigns.approve','campaigns.reject'],'Template Designer'=>['templates.*'],'Contact Manager'=>['contacts.*'],'Automation Manager'=>['automations.*'],'Analyst'=>['dashboard.view','analytics.*','reports.*'],'Viewer'=>['dashboard.view','contacts.view','campaigns.view','templates.view','analytics.view'],'Support Agent'=>['dashboard.view','contacts.view','campaigns.view','team.view']];foreach($presets as$name=>$permissions)$this->db->table('role_presets')->insert(['name'=>$name,'scope'=>'system','permissions'=>json_encode($permissions),'created_at'=>$now,'updated_at'=>$now]);
    }
    public function down():void{$this->forge->dropTable('permission_change_history',true);$this->forge->dropTable('permission_definitions',true);}
}
