<?php
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;
class ExpandContactDomain extends Migration
{
    public function up():void
    {
        if(!$this->db->fieldExists('uuid','contacts'))$this->forge->addColumn('contacts',[
            'uuid'=>['type'=>'CHAR','constraint'=>36,'null'=>true,'after'=>'id'],'reseller_id'=>['type'=>'INT','unsigned'=>true,'null'=>true,'after'=>'workspace_id'],'normalized_email'=>['type'=>'VARCHAR','constraint'=>190,'null'=>true,'after'=>'email'],'company'=>['type'=>'VARCHAR','constraint'=>190,'null'=>true],'job_title'=>['type'=>'VARCHAR','constraint'=>190,'null'=>true],'website'=>['type'=>'VARCHAR','constraint'=>500,'null'=>true],'address_line_1'=>['type'=>'VARCHAR','constraint'=>255,'null'=>true],'address_line_2'=>['type'=>'VARCHAR','constraint'=>255,'null'=>true],'city'=>['type'=>'VARCHAR','constraint'=>100,'null'=>true],'state'=>['type'=>'VARCHAR','constraint'=>100,'null'=>true],'postal_code'=>['type'=>'VARCHAR','constraint'=>30,'null'=>true],'country'=>['type'=>'VARCHAR','constraint'=>100,'null'=>true],'latitude'=>['type'=>'DECIMAL','constraint'=>'10,7','null'=>true],'longitude'=>['type'=>'DECIMAL','constraint'=>'10,7','null'=>true],'google_place_id'=>['type'=>'VARCHAR','constraint'=>255,'null'=>true],'source_reference'=>['type'=>'VARCHAR','constraint'=>500,'null'=>true],'notes'=>['type'=>'TEXT','null'=>true],'consent_status'=>['type'=>'VARCHAR','constraint'=>50,'null'=>true],'consent_source'=>['type'=>'VARCHAR','constraint'=>190,'null'=>true],'consent_ip'=>['type'=>'VARCHAR','constraint'=>50,'null'=>true],'consented_at'=>['type'=>'DATETIME','null'=>true],'last_opened_at'=>['type'=>'DATETIME','null'=>true],'last_clicked_at'=>['type'=>'DATETIME','null'=>true],'last_emailed_at'=>['type'=>'DATETIME','null'=>true],'score'=>['type'=>'INT','default'=>0],'owner_user_id'=>['type'=>'INT','unsigned'=>true,'null'=>true],'created_by'=>['type'=>'INT','unsigned'=>true,'null'=>true]
        ]);
        $this->db->query("UPDATE contacts SET uuid=UUID(),normalized_email=LOWER(TRIM(email)) WHERE uuid IS NULL");$indexes=array_keys($this->db->getIndexData('contacts'));if(!in_array('uq_contacts_uuid',$indexes,true))$this->db->query('ALTER TABLE contacts ADD UNIQUE KEY uq_contacts_uuid (uuid)');if(!in_array('uq_contacts_workspace_normalized_email',$indexes,true))$this->db->query('ALTER TABLE contacts ADD UNIQUE KEY uq_contacts_workspace_normalized_email (workspace_id,normalized_email)');if(!in_array('idx_contacts_google_place_id',$indexes,true))$this->db->query('ALTER TABLE contacts ADD KEY idx_contacts_google_place_id (google_place_id)');
        $this->table('contact_lists',['workspace_id'=>'INT','reseller_id'=>'INT','uuid'=>'CHAR(36)','name'=>'VARCHAR(150)','description'=>'TEXT NULL','color'=>'VARCHAR(10)','contacts_count'=>'BIGINT','created_by'=>'INT','created_at'=>'DATETIME','updated_at'=>'DATETIME'],[['uuid'],['workspace_id','name']]);
        $this->table('contact_list_members',['list_id'=>'INT','contact_id'=>'INT','added_by'=>'INT','created_at'=>'DATETIME'],[['list_id','contact_id']]);
        $this->table('custom_field_definitions',['workspace_id'=>'INT','uuid'=>'CHAR(36)','name'=>'VARCHAR(150)','field_key'=>'VARCHAR(100)','field_type'=>'VARCHAR(30)','options'=>'LONGTEXT NULL','is_required'=>'TINYINT','created_at'=>'DATETIME','updated_at'=>'DATETIME'],[['uuid'],['workspace_id','field_key']]);
        $this->table('contact_activities',['workspace_id'=>'INT','contact_id'=>'INT','user_id'=>'INT NULL','event_type'=>'VARCHAR(80)','description'=>'VARCHAR(500)','metadata'=>'LONGTEXT NULL','occurred_at'=>'DATETIME'],[]);
        $this->table('contact_suppressions',['workspace_id'=>'INT','contact_id'=>'INT NULL','email'=>'VARCHAR(190)','reason'=>'VARCHAR(40)','source'=>'VARCHAR(100)','campaign_id'=>'INT NULL','created_by'=>'INT NULL','created_at'=>'DATETIME'],[['workspace_id','email']]);
        $this->table('contact_imports',['uuid'=>'CHAR(36)','workspace_id'=>'INT','reseller_id'=>'INT NULL','uploaded_by'=>'INT','original_filename'=>'VARCHAR(500)','stored_filename'=>'VARCHAR(500)','file_type'=>'VARCHAR(10)','mapping'=>'LONGTEXT NULL','options'=>'LONGTEXT NULL','status'=>'VARCHAR(30)','total_rows'=>'BIGINT','processed_rows'=>'BIGINT','created_rows'=>'BIGINT','updated_rows'=>'BIGINT','skipped_rows'=>'BIGINT','invalid_rows'=>'BIGINT','error_report'=>'VARCHAR(500) NULL','error_message'=>'TEXT NULL','started_at'=>'DATETIME NULL','completed_at'=>'DATETIME NULL','created_at'=>'DATETIME','updated_at'=>'DATETIME'],[['uuid']]);
        $this->table('contact_import_errors',['import_id'=>'INT','row_number'=>'BIGINT','email'=>'VARCHAR(190) NULL','errors'=>'TEXT','raw_data'=>'LONGTEXT NULL','created_at'=>'DATETIME'],[]);
        $this->table('contact_merge_history',['workspace_id'=>'INT','primary_contact_id'=>'INT','merged_contact_id'=>'INT','merged_by'=>'INT','snapshot'=>'LONGTEXT','created_at'=>'DATETIME'],[]);
    }
    private function table(string$name,array$fields,array$unique):void{$defs=['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true]];foreach($fields as$key=>$sql){$parts=explode(' ',$sql,2);$type=$parts[0];$null=str_contains($sql,' NULL');if(preg_match('/^([A-Z]+)\(([^)]+)\)$/',$type,$m))$defs[$key]=['type'=>$m[1],'constraint'=>$m[2],'null'=>$null];else$defs[$key]=['type'=>$type,'null'=>$null];if(in_array($key,['workspace_id','reseller_id','created_by','uploaded_by','user_id','contact_id','list_id','added_by','campaign_id','primary_contact_id','merged_contact_id','merged_by'],true))$defs[$key]['unsigned']=true;}$this->forge->addField($defs);$this->forge->addKey('id',true);foreach($unique as$keys)$this->forge->addUniqueKey($keys);if(isset($fields['workspace_id']))$this->forge->addKey('workspace_id');$this->forge->createTable($name);}
    public function down():void{foreach(['contact_merge_history','contact_import_errors','contact_imports','contact_suppressions','contact_activities','custom_field_definitions','contact_list_members','contact_lists']as$t)$this->forge->dropTable($t,true);}
}
