<?php
namespace App\Controllers;
use App\Libraries\AuditLogService;use App\Libraries\WorkspaceProvisioner;use App\Models\UserModel;use App\Support\Uuid;
class Auth extends BaseController
{
    public function login() { if(app_auth()->loggedIn())return redirect()->to('/');return view('auth/login'); }
    public function authenticate(){if(!app_auth()->attempt((string)$this->request->getPost('email'),(string)$this->request->getPost('password')))return redirect()->back()->withInput()->with('error','Invalid credentials or too many attempts.');return redirect()->to('/');}
    public function register() { if(app_auth()->loggedIn())return redirect()->to('/');return view('auth/register'); }
    public function store(){ $rules=['first_name'=>'required|min_length[2]|max_length[100]','last_name'=>'permit_empty|max_length[100]','company_name'=>'required|max_length[150]','email'=>'required|valid_email|max_length[190]|is_unique[users.email]','password'=>'required|min_length[10]','password_confirm'=>'required|matches[password]'];if(!$this->validateData($this->request->getPost(),$rules))return redirect()->back()->withInput()->with('errors',$this->validator->getErrors());$brandReseller=service('brandContext')->get('reseller_id');$model=new UserModel();$id=$model->insert(['uuid'=>Uuid::v4(),'account_level'=>5,'account_type'=>'customer','user_type'=>'customer','parent_user_id'=>$brandReseller,'reseller_id'=>$brandReseller,'workspace_role'=>'owner','username'=>$this->request->getPost('first_name'),'first_name'=>$this->request->getPost('first_name'),'last_name'=>$this->request->getPost('last_name'),'company_name'=>$this->request->getPost('company_name'),'email'=>strtolower(trim((string)$this->request->getPost('email'))),'password_hash'=>password_hash((string)$this->request->getPost('password'),PASSWORD_DEFAULT),'status'=>'active','active'=>1,'email_verified_at'=>date('Y-m-d H:i:s'),'session_version'=>1]);if(!$id)return redirect()->back()->withInput()->with('errors',$model->errors());$user=$model->find($id);(new WorkspaceProvisioner())->ensureForUser($user);(new AuditLogService())->record('auth.register',$user,[],'user',$user['uuid']);app_auth()->attempt($user['email'],(string)$this->request->getPost('password'));return redirect()->to('/'); }
    public function logout(){app_auth()->logout();return redirect()->to('/login')->with('message','You have signed out.');}
}
