<?php
namespace App\Libraries;
use App\Models\ContactModel;use App\Models\UserModel;use App\Support\Uuid;use CodeIgniter\HTTP\Files\UploadedFile;
class ContactImportService
{
    public function stage(array$user,UploadedFile$file,array$options=[]):string
    {
        if(!(new PermissionService())->allows($user,'contacts.import',(int)$user['workspace_id']))throw new \DomainException('Permission denied.');
        if(!$file->isValid())throw new \InvalidArgumentException('Choose a valid import file.');$ext=strtolower($file->getExtension());if(!in_array($ext,['csv','xls','xlsx'],true))throw new \InvalidArgumentException('Only CSV, XLS and XLSX files are allowed.');if($file->getSize()>20*1024*1024)throw new \InvalidArgumentException('Import files are limited to 20 MB.');if($ext!=='csv'&&!class_exists(\PhpOffice\PhpSpreadsheet\IOFactory::class))throw new \RuntimeException('XLS/XLSX support requires PhpSpreadsheet and the PHP GD extension.');
        $dir=WRITEPATH.'uploads/contact-imports';if(!is_dir($dir))mkdir($dir,0700,true);$stored=bin2hex(random_bytes(16)).'.'.$ext;$file->move($dir,$stored);$uuid=Uuid::v4();$now=date('Y-m-d H:i:s');db_connect()->table('contact_imports')->insert(['uuid'=>$uuid,'workspace_id'=>$user['workspace_id'],'reseller_id'=>$user['reseller_id']?:null,'uploaded_by'=>$user['id'],'original_filename'=>$file->getClientName(),'stored_filename'=>$stored,'file_type'=>$ext,'mapping'=>json_encode($options['mapping']??[]),'options'=>json_encode($options),'status'=>'queued','total_rows'=>0,'processed_rows'=>0,'created_rows'=>0,'updated_rows'=>0,'skipped_rows'=>0,'invalid_rows'=>0,'created_at'=>$now,'updated_at'=>$now]);return$uuid;
    }
    public function processNext():bool
    {
        $db=db_connect();$job=$db->table('contact_imports')->where('status','queued')->orderBy('id','ASC')->get()->getRowArray();if(!$job)return false;$db->table('contact_imports')->where('id',$job['id'])->update(['status'=>'processing','started_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);try{$this->process($job);return true;}catch(\Throwable$e){$db->table('contact_imports')->where('id',$job['id'])->update(['status'=>'failed','error_message'=>substr($e->getMessage(),0,2000),'completed_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);return true;}}
    private function process(array$job):void
    {
        if($job['file_type']!=='csv')throw new \RuntimeException('Spreadsheet adapter is not installed.');$path=WRITEPATH.'uploads/contact-imports/'.$job['stored_filename'];$h=fopen($path,'rb');if(!$h)throw new \RuntimeException('Stored import file is missing.');$headers=array_map(fn($v)=>strtolower(trim((string)$v)),fgetcsv($h)?:[]);$mapping=json_decode((string)$job['mapping'],true)?:[];$options=json_decode((string)$job['options'],true)?:[];$mode=$options['duplicate_mode']??'skip';$db=db_connect();$user=(new UserModel())->find($job['uploaded_by']);$counts=['total_rows'=>0,'processed_rows'=>0,'created_rows'=>0,'updated_rows'=>0,'skipped_rows'=>0,'invalid_rows'=>0];$rowNo=1;
        while(($row=fgetcsv($h))!==false){$rowNo++;$counts['total_rows']++;$raw=array_combine($headers,array_pad($row,count($headers),''));$data=[];foreach($raw?:[] as$key=>$value)$data[$mapping[$key]??$key]=trim((string)$value);$email=strtolower($data['email']??'');if(!filter_var($email,FILTER_VALIDATE_EMAIL)){$this->error($job['id'],$rowNo,$email,'Invalid or missing email',$raw?:[]);$counts['invalid_rows']++;continue;}$existing=(new ContactModel())->where(['workspace_id'=>$job['workspace_id'],'normalized_email'=>$email])->first();if($existing){if($mode==='skip'){$counts['skipped_rows']++;continue;}$allowed=array_intersect_key($data,array_flip(['first_name','last_name','phone','company','job_title','website','city','state','postal_code','country']));if($mode==='update_blank')foreach($allowed as$k=>$v)if(($existing[$k]??'')!=='')unset($allowed[$k]);(new ContactModel())->update($existing['id'],$allowed);$counts['updated_rows']++;}else{try{(new ContactService())->create($user,$data+['source'=>'import']);$counts['created_rows']++;}catch(\Throwable$e){$this->error($job['id'],$rowNo,$email,$e->getMessage(),$raw?:[]);$counts['invalid_rows']++;}}$counts['processed_rows']++;if($counts['total_rows']%100===0)$db->table('contact_imports')->where('id',$job['id'])->update($counts+['updated_at'=>date('Y-m-d H:i:s')]);}
        fclose($h);$db->table('contact_imports')->where('id',$job['id'])->update($counts+['status'=>'completed','completed_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);
    }
    private function error(int$id,int$row,string$email,string$error,array$raw):void{db_connect()->table('contact_import_errors')->insert(['import_id'=>$id,'row_number'=>$row,'email'=>$email?:null,'errors'=>$error,'raw_data'=>json_encode($raw),'created_at'=>date('Y-m-d H:i:s')]);}
}
