<?php $brand=service('brandContext')->all(); ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= esc($title ?? $brand['name']) ?> · <?= esc($brand['name']) ?></title><?php if($brand['favicon_path']): ?><link rel="icon" href="<?= esc(base_url($brand['favicon_path'])) ?>"><?php endif ?><script src="https://cdn.tailwindcss.com"></script><script src="https://unpkg.com/lucide@latest"></script><script>tailwind.config={theme:{extend:{colors:{ink:'#183B3B',mist:'#EEF7F5',mint:'<?= esc($brand['primary_color'],'js') ?>',sea:'<?= esc($brand['secondary_color'],'js') ?>'},boxShadow:{soft:'10px 10px 25px rgba(46,101,94,.10),-10px -10px 25px rgba(255,255,255,.88)',insetsoft:'inset 4px 4px 10px rgba(46,101,94,.10),inset -4px -4px 10px rgba(255,255,255,.85)'}}}}</script><link rel="stylesheet" href="<?= base_url('assets/app.css') ?>"></head>
<body class="bg-mist text-ink"><div class="min-h-screen lg:flex">
<aside id="sidebar" class="fixed z-40 h-screen w-64 border-r border-white/70 bg-mist p-5 lg:sticky lg:top-0"><div class="flex items-center justify-between"><a href="<?= base_url() ?>" class="brand flex items-center gap-2 text-xl font-extrabold"><?php if($brand['logo_path']): ?><img src="<?= esc(base_url($brand['logo_path'])) ?>" alt="<?= esc($brand['name']) ?>" class="h-10 max-w-36 object-contain"><?php else: ?><span class="grid h-10 w-10 place-items-center rounded-2xl bg-gradient-to-br from-mint to-sea text-white shadow-soft"><i data-lucide="send" class="h-5"></i></span><?= esc(strtolower($brand['name'])) ?><span class="text-mint">.</span><?php endif ?></a><button id="closeNav" class="lg:hidden"><i data-lucide="x"></i></button></div>
<?php $viewer=current_user();$inWorkspace=$viewer['account_type']==='customer'||session('active_workspace_id');$nav=[['dashboard','layout-dashboard','Overview',$inWorkspace?workspace_url('dashboard'):portal_url('dashboard')]];if($viewer['account_type']==='platform_admin'&&!$inWorkspace)$nav=array_merge($nav,[['admin-users','users','Users',base_url('admin/users')],['admin-resellers','store','Resellers',base_url('admin/resellers')],['admin-plans','package','Packages',base_url('admin/plans')],['admin-payments','credit-card','Payments',base_url('admin/payments')],['admin-workers','cpu','Worker setup',base_url('admin/workers')],['admin-settings','settings-2','Admin Settings',base_url('admin/settings')]]);if($inWorkspace)$nav=array_merge($nav,[['contacts','users','Contacts',workspace_url('contacts')],['campaigns','mail','Campaigns',workspace_url('campaigns')],['automations','workflow','Automation',workspace_url('automations')],['forms','panel-top','Forms & Pages',workspace_url('forms')],['templates','panels-top-left','Templates',workspace_url('templates')],['analytics','chart-no-axes-combined','Analytics',workspace_url('analytics')],['team','user-round-cog','Team',workspace_url('team')],['settings','settings-2','Settings',workspace_url('settings')]]);if(in_array($viewer['account_type'],['platform_admin','platform_team','reseller','reseller_team'],true))$nav[]=['clients','briefcase-business','Clients',portal_url('clients')];if(in_array($viewer['account_type'],['platform_admin','platform_team','reseller','reseller_team'],true))$nav[]=['accounts','building-2','Accounts',portal_url('accounts')];if(in_array($viewer['account_type'],['reseller','reseller_team'],true))$nav[]=['branding','palette','White label',portal_url('branding')]; ?>
<nav class="mt-10 space-y-1 text-sm font-semibold"><?php foreach($nav as $n): ?><a href="<?= esc($n[3]) ?>" class="nav-link <?= $active===$n[0]?'active':'' ?> relative flex items-center gap-3 rounded-xl px-3 py-3 text-[#6f8d88]"><i data-lucide="<?= $n[1] ?>" class="h-[18px]"></i><?= $n[2] ?></a><?php endforeach ?></nav>
<div class="absolute bottom-6 left-5 right-5 rounded-2xl bg-[#e5f1ee] p-3 shadow-insetsoft"><div class="mb-2 flex justify-between text-xs font-semibold"><span>Monthly emails</span><span>68%</span></div><div class="h-1.5 rounded-full bg-white"><div class="h-full w-[68%] rounded-full bg-gradient-to-r from-mint to-sea"></div></div><p class="mt-2 text-[11px] text-[#77928e]">68,240 of 100,000 used</p></div></aside>
<?php $currentUser=current_user(); $displayName=trim(($currentUser['first_name']??'').' '.($currentUser['last_name']??'')) ?: ($currentUser['email']??'User'); $initials=strtoupper(substr($displayName,0,2)); ?>
<main class="min-w-0 flex-1 px-4 pb-12 sm:px-8"><header class="sticky top-0 z-30 -mx-4 flex h-20 items-center justify-between border-b border-white/70 bg-mist/90 px-4 backdrop-blur sm:-mx-8 sm:px-8"><div class="flex items-center gap-3"><button id="openNav" class="grid h-10 w-10 place-items-center rounded-xl shadow-soft lg:hidden"><i data-lucide="menu"></i></button><div><p class="text-xs font-semibold text-[#819b97]"><?= date('l, F j') ?></p><h1 class="text-2xl font-extrabold"><?= esc($title ?? '') ?></h1></div></div><div class="flex items-center gap-3"><button id="openHeaderMenu" type="button" class="grid h-10 w-10 place-items-center rounded-xl shadow-soft" title="Quick actions"><i data-lucide="settings-2" class="h-4"></i></button><button class="grid h-10 w-10 place-items-center rounded-xl shadow-soft"><i data-lucide="bell" class="h-4"></i></button><div class="hidden text-right sm:block"><p class="text-xs font-bold"><?= esc($displayName) ?></p><a href="<?= base_url('logout') ?>" class="text-[11px] font-semibold text-sea">Sign out</a></div></div></header>
<dialog id="headerSettingsMenu" class="w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl backdrop:bg-[#153b39]/30">
    <div class="flex items-center justify-between gap-4"><div><h3 class="text-lg font-extrabold">Quick actions</h3><p class="text-sm text-[#78908c]">Open the email or workspace settings.</p></div><button type="button" onclick="document.getElementById('headerSettingsMenu').close()" class="btn btn-soft btn-sm">Close</button></div>
    <div class="mt-5 space-y-3">
        <button type="button" onclick="window.location.href='<?= workspace_url('settings?open=smtp') ?>'" class="btn btn-primary w-full">Email account</button>
        <button type="button" onclick="window.location.href='<?= workspace_url('settings?open=workspace') ?>'" class="btn btn-secondary w-full">Workspace & white label</button>
    </div>
</dialog>
<?php if(session('success')): ?><div class="mt-5 rounded-xl bg-[#dff4e9] px-4 py-3 text-sm font-semibold text-[#23785f]"><?= esc(session('success')) ?></div><?php endif ?><?php if(session('error')): ?><div class="mt-5 rounded-xl bg-[#f8e6df] px-4 py-3 text-sm font-semibold text-[#a4573a]"><?= esc(session('error')) ?></div><?php endif ?><?= $content ?></main></div>
<script>lucide.createIcons();const s=document.getElementById('sidebar');document.getElementById('openNav').onclick=()=>s.classList.add('open');document.getElementById('closeNav').onclick=()=>s.classList.remove('open');const openHeaderMenu=document.getElementById('openHeaderMenu');openHeaderMenu?.addEventListener('click',()=>document.getElementById('headerSettingsMenu').showModal());</script></body></html>
