<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= esc($title ?? 'Mailora') ?> · Mailora</title><script src="https://cdn.tailwindcss.com"></script><script src="https://unpkg.com/lucide@latest"></script><script>tailwind.config={theme:{extend:{colors:{ink:'#183B3B',mist:'#EEF7F5',mint:'#44B89D',sea:'#288DA5'},boxShadow:{soft:'10px 10px 25px rgba(46,101,94,.10),-10px -10px 25px rgba(255,255,255,.88)',insetsoft:'inset 4px 4px 10px rgba(46,101,94,.10),inset -4px -4px 10px rgba(255,255,255,.85)'}}}}</script><link rel="stylesheet" href="<?= base_url('assets/app.css') ?>"></head>
<body class="bg-mist text-ink"><div class="min-h-screen lg:flex">
<aside id="sidebar" class="fixed z-40 h-screen w-64 border-r border-white/70 bg-mist p-5 lg:sticky lg:top-0"><div class="flex items-center justify-between"><a href="<?= base_url() ?>" class="brand flex items-center gap-2 text-xl font-extrabold"><span class="grid h-10 w-10 place-items-center rounded-2xl bg-gradient-to-br from-mint to-sea text-white shadow-soft"><i data-lucide="send" class="h-5"></i></span>mailora<span class="text-mint">.</span></a><button id="closeNav" class="lg:hidden"><i data-lucide="x"></i></button></div>
<?php $nav=[['dashboard','layout-dashboard','Overview','/'],['contacts','users','Contacts','/contacts'],['campaigns','mail','Campaigns','/campaigns'],['automations','workflow','Automation','/automations'],['forms','panel-top','Forms & Pages','/forms'],['templates','panels-top-left','Templates','/templates'],['analytics','chart-no-axes-combined','Analytics','/analytics'],['team','user-round-cog','Team','/team'],['settings','settings-2','Settings','/settings']]; ?>
<nav class="mt-10 space-y-1 text-sm font-semibold"><?php foreach($nav as $n): ?><a href="<?= base_url(ltrim($n[3],'/')) ?>" class="nav-link <?= $active===$n[0]?'active':'' ?> relative flex items-center gap-3 rounded-xl px-3 py-3 text-[#6f8d88]"><i data-lucide="<?= $n[1] ?>" class="h-[18px]"></i><?= $n[2] ?></a><?php endforeach ?></nav>
<div class="absolute bottom-6 left-5 right-5 rounded-2xl bg-[#e5f1ee] p-3 shadow-insetsoft"><div class="mb-2 flex justify-between text-xs font-semibold"><span>Monthly emails</span><span>68%</span></div><div class="h-1.5 rounded-full bg-white"><div class="h-full w-[68%] rounded-full bg-gradient-to-r from-mint to-sea"></div></div><p class="mt-2 text-[11px] text-[#77928e]">68,240 of 100,000 used</p></div></aside>
<main class="min-w-0 flex-1 px-4 pb-12 sm:px-8"><header class="sticky top-0 z-30 -mx-4 flex h-20 items-center justify-between border-b border-white/70 bg-mist/90 px-4 backdrop-blur sm:-mx-8 sm:px-8"><div class="flex items-center gap-3"><button id="openNav" class="grid h-10 w-10 place-items-center rounded-xl shadow-soft lg:hidden"><i data-lucide="menu"></i></button><div><p class="text-xs font-semibold text-[#819b97]"><?= date('l, F j') ?></p><h1 class="text-2xl font-extrabold"><?= esc($title ?? '') ?></h1></div></div><div class="flex items-center gap-3"><button class="grid h-10 w-10 place-items-center rounded-xl shadow-soft"><i data-lucide="bell" class="h-4"></i></button><div class="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-[#c9f26b] to-mint font-bold text-white">OM</div></div></header>
<?php if(session('success')): ?><div class="mt-5 rounded-xl bg-[#dff4e9] px-4 py-3 text-sm font-semibold text-[#23785f]"><?= esc(session('success')) ?></div><?php endif ?><?php if(session('error')): ?><div class="mt-5 rounded-xl bg-[#f8e6df] px-4 py-3 text-sm font-semibold text-[#a4573a]"><?= esc(session('error')) ?></div><?php endif ?><?= $content ?></main></div>
<script>lucide.createIcons();const s=document.getElementById('sidebar');document.getElementById('openNav').onclick=()=>s.classList.add('open');document.getElementById('closeNav').onclick=()=>s.classList.remove('open');</script></body></html>
